name: fulltimeforce_challenge
description: My app for watch the commits of the project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.3
  bloc_test: ^9.1.4
  domain:
    path: packages/domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.1.0
  intl: ^0.18.0
  shimmer: ^3.0.0
  stacked_card_carousel: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/img/
    - assets/fonts/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf